### get all the movies

GET http://localhost:1234/movies

### Get movie by id

GET http://localhost:1234/movies/6276e5ad-9c38-11ee-8962-04d4c44c7252

### Get all the movies with the genre 

GET http://localhost:1234/movies?genre=Drama

### Create a movie 

POST http://localhost:1234/movies
Content-Type: application/json

    {
        "title": "The Godfather",
        "year": 1975,
        "director": "Francis Ford Coppola",
        "duration": 175,
        "rate": 8.4,
        "poster": "http://img.fruugo.com/product/4/49/14441494_max.jpg",
        "genre": [
            "Drama",
            "Crime"
        ]
    }

### Delete a movie

DELETE http://localhost:1234/movies/5506ca1c-9d16-11ee-8962-04d4c44c7252

### Update data from movie

PATCH http://localhost:1234/movies/627c688b-9d18-11ee-8962-04d4c44c7252
Content-Type: application/json

{
    "year": 2010,
    "director": "Moro Hernandez"
}